### ISSUE TITLE
all Boxes have same props

### ISSUE THREAD

**Issue by marek-sed** [sultan99/react-on-lambda#1]
Hey love the idea.
is this on purpose or a bug?

same props on all boxes

```
import r from "rol";
import s from "styled-components";
import { space, layout, color } from "styled-system";

const Box = r.div`${layout} ${space} ${color}`;

function Home() {
  return r.compose(
    r.section,
    Box({ m: 50, backgroundColor: "pink" }),
    r.compose(
      Box({ m: 0 }),
      Box({ color: "blue" }),
      Box({ pt: 100 })
    )
  )("hello world");
}```

**Comment by sultan99** [comment]
Hi @marek-sed!
Thanks for reporting, I have checked it, looks like is a bug with styled-components.
Now I will try to fix it.

**Comment by sultan99** [comment]
@marek-sed 
The bug is fixed!

You can check it [here online](https://codesandbox.io/s/rol-fix-issue1-rh9dk).

**Comment by marek-sed** [comment]
thank you awesome :)
